---

- name: ks-devops | Setting external sonarqube url
  set_fact:
    externalSonarUrl: "{{ devops.sonarqube.externalSonarUrl }}"
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is defined
    - devops.sonarqube.externalSonarToken is defined

- name: ks-devops | Setting ks-sonarqube token
  set_fact:
    externalSonarToken: "{{ devops.sonarqube.externalSonarToken }}"
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is defined
    - devops.sonarqube.externalSonarToken is defined

- import_tasks: check_sonar.yaml
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is not defined
    - devops.sonarqube.externalSonarToken is not defined

- import_tasks: sonar_token.yaml
  when:
    - sonar_health is defined and sonar_health == true

- name: ks-devops | Getting jenkins installation files
  copy:
    src: "jenkins"
    dest: "{{ kubesphere_dir }}/"


- name: Jenkins | Check jenkins status
  shell: >
    {{ bin_dir }}/kubectl get deploy -n kubesphere-devops-system ks-jenkins
  register: jenkins_status
  ignore_errors: True

- import_tasks: get_old_config.yaml
  when:
    - jenkins_status.rc == 0

#- name: Jenkins | Check Jenkins
#  shell: >
#    {{ bin_dir }}/helm list ks-jenkins
#  register: jenkins_check
#  ignore_errors: True

- name: Jenkins | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/jenkins/{{ item.file }}"
  with_items:
    - { name: custom-values-jenkins, file: custom-values-jenkins.yaml }
    - { name: jenkins-casc-config, file: jenkins-casc-config.yml }
    - { name: jenkins-agent-config, file: jenkins-agent-config.yaml}


- name: Jenkins | Configure Jenkins host and port
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/jenkins/jenkins-casc-config.yml --namespace kubesphere-devops-system


- name: Jenkins | Create Jenkins Agent Config File
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/jenkins/jenkins-agent-config.yaml --namespace kubesphere-devops-system


- name: Jenkins | Deploy Jenkins
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-jenkins {{ kubesphere_dir }}/jenkins/jenkins
    -f {{ kubesphere_dir }}/jenkins/custom-values-jenkins.yaml
    --namespace kubesphere-devops-system
#  when:
#    - (jenkins_check.stdout.find("DEPLOYED") == -1) or (jenkins_check.stdout.find("2.121.3-0217") == -1)


- name: ks-devops | import ks-devops status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"devops": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3