---
- name: Kubesphere | Checking account init
  shell: >
    {{ bin_dir }}/kubectl get users admin
  register: kubesphere_user_check
  failed_when: "kubesphere_user_check.stderr and 'NotFound' not in kubesphere_user_check.stderr"

- name: Kubesphere | Init account
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-init/admin.yaml
  when:
    - kubesphere_user_check.stderr is defined
    - kubesphere_user_check.stderr.find("NotFound") != -1


- name: KubeSphere | Init KubeSphere
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-init/{{ item }}"
  loop:
    - "iam-accounts.yaml"
    - "webhook-secret.yaml"
    - "users.iam.kubesphere.io.yaml"
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr and 'Warning' not in import.stderr"
