apiVersion: v1
kind: Service
metadata:
  name: hyperpitrix
  labels:
    app: openpitrix
    component: openpitrix-hyperpitrix
    version: {{ .Values.version }}
spec:
  selector:
    app: openpitrix
    component: openpitrix-hyperpitrix
  ports:
    - name: openpitrix-rp-kubernetes
      protocol: TCP
      port: 9123
      targetPort: 9123
    - name: openpitrix-rp-manager
      protocol: TCP
      port: 9121
      targetPort: 9121
    - name: openpitrix-api-gateway
      protocol: TCP
      port: 9100
      targetPort: 9100
    - name: openpitrix-app-manager
      protocol: TCP
      port: 9102
      targetPort: 9102
    - name: openpitrix-category-manager
      protocol: TCP
      port: 9113
      targetPort: 9113
    - name: openpitrix-attachment-manager
      protocol: TCP
      port: 9122
      targetPort: 9122
    - name: openpitrix-cluster-manager
      protocol: TCP
      port: 9104
      targetPort: 9104
    - name: openpitrix-isv-manager
      protocol: TCP
      port: 9118
      targetPort: 9118
    - name: openpitrix-job-manager
      protocol: TCP
      port: 9106
      targetPort: 9106
    - name: openpitrix-repo-manager
      protocol: TCP
      port: 9101
      targetPort: 9101
    - name: openpitrix-repo-indexer
      protocol: TCP
      port: 9108
      targetPort: 9108
    - name: openpitrix-runtime-manager
      protocol: TCP
      port: 9103
      targetPort: 9103
    - name: openpitrix-task-manager
      protocol: TCP
      port: 9107
      targetPort: 9107