---

- name: Kubefed | Getting kubefed installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "kubefed"

- name: Kubefed | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: kubefed, file: custom-values-kubefed.yaml }
    - { path: kubefed, file: tower.yaml }

- name: Kubefed | Check kubefed
  shell: >
    {{ bin_dir }}/helm list --namespace kube-federation-system | grep "kubefed"
  register: kubefed_check
  ignore_errors: True

- block:
    - name: Tower | Install tower
      shell: >
        {{ bin_dir }}/kubectl -n kubesphere-system apply -f {{ kubesphere_dir }}/kubefed/tower.yaml
      register: tower_result
      ignore_errors: False

    - name: Kubefed | Init kube-federation-system
      shell: >
        {{ bin_dir }}/helm upgrade --install kubefed {{ kubesphere_dir }}/kubefed/kubefed
        -f {{ kubesphere_dir }}/kubefed/custom-values-kubefed.yaml
        --namespace kube-federation-system

    - name: Kubfed | Label kube-federation-system namespace
      shell: >
        {{ bin_dir }}/kubectl label namespace kube-federation-system kubesphere.io/workspace=system-workspace --overwrite


- name: Kubesphere | Check kubefed-admission-webhook status
  wait_for:
    host: "kubefed-admission-webhook.kube-federation-system.svc"
    port: 443
    delay: 5
    timeout: 1800


- name: Kubefed | Create MultiCluster crds
  shell: "{{ bin_dir }}/kubectl create -f {{ item }} -n kube-federation-system"
  register: crds_result
  failed_when: "crds_result.stderr and 'AlreadyExists' not in crds_result.stderr"
  until: crds_result is succeeded
  retries: 5
  delay: 5
  with_fileglob:
    - "{{ kubesphere_dir }}/kubefed/federatedcrds/*"


- name: Kubefed | import multicluster status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"multicluster": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3
