---
apiVersion: core.kubefed.io/v1beta1
kind: FederatedTypeConfig
metadata:
  name: serviceaccounts
spec:
  federatedType:
    group: types.kubefed.io
    kind: FederatedServiceAccount
    pluralName: federatedserviceaccounts
    scope: Namespaced
    version: v1beta1
  propagation: Enabled
  targetType:
    kind: ServiceAccount
    pluralName: serviceaccounts
    scope: Namespaced
    version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedserviceaccounts.types.kubefed.io
spec:
  group: types.kubefed.io
  names:
    kind: FederatedServiceAccount
    plural: federatedserviceaccounts
    shortNames:
    - fsa
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            overrides:
              items:
                properties:
                  clusterName:
                    type: string
                  clusterOverrides:
                    items:
                      properties:
                        op:
                          pattern: ^(add|remove|replace)?$
                          type: string
                        path:
                          type: string
                        value:
                          anyOf:
                          - type: string
                          - type: integer
                          - type: boolean
                          - type: object
                          - type: array
                      required:
                      - path
                      type: object
                    type: array
                type: object
              type: array
            placement:
              properties:
                clusterSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                clusters:
                  items:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
              type: object
            template:
              type: object
          type: object
        status:
          properties:
            clusters:
              items:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                required:
                - name
                type: object
              type: array
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
          type: object
      required:
      - spec
  version: v1beta1
