---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: openpitrix
      when:
        - "status.openpitrix is not defined or status.openpitrix.status is not defined or status.openpitrix.status != 'enabled'"