apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: emailconfigs.notification.kubesphere.io
spec:
  conversion:
    strategy: None
  group: notification.kubesphere.io
  names:
    kind: EmailConfig
    listKind: EmailConfigList
    plural: emailconfigs
    singular: emailconfig
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: EmailConfig is the Schema for the emailconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EmailConfigSpec defines the desired state of EmailConfig
          properties:
            authIdentify:
              description: The identity for PLAIN authentication.
              type: string
            authPassword:
              description: The secret contains the SMTP password for LOGIN and PLAIN
                authentications.
              properties:
                key:
                  description: The key of the secret to select from.  Must be a valid
                    secret key.
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                            TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
                optional:
                  description: Specify whether the Secret or its key must be defined
                  type: boolean
              required:
                - key
              type: object
            authSecret:
              description: The secret contains the SMTP secret for CRAM-MD5 authentication.
              properties:
                key:
                  description: The key of the secret to select from.  Must be a valid
                    secret key.
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                            TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
                optional:
                  description: Specify whether the Secret or its key must be defined
                  type: boolean
              required:
                - key
              type: object
            authUsername:
              description: The username for CRAM-MD5, LOGIN and PLAIN authentications.
              type: string
            from:
              description: The sender address.
              type: string
            hello:
              description: The hostname to use when identifying to the SMTP server.
              type: string
            requireTLS:
              description: The default SMTP TLS requirement.
              type: boolean
            smartHost:
              description: The address of the SMTP server.
              properties:
                host:
                  type: string
                port:
                  type: string
              required:
                - host
                - port
              type: object
          required:
            - from
            - smartHost
          type: object
        status:
          description: EmailConfigStatus defines the observed state of EmailConfig
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
